[phases.setup]
nixPkgs = ["gcc", "pkg-config", "libmariadb-dev", "libmariadb-dev-compat", "nodejs", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build && cd ..",
    "python manage.py collectstatic --noinput --settings=Stackin.settings_production"
]

[start]
cmd = "gunicorn Stackin.wsgi:application --bind 0.0.0.0:$PORT"
