[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build && cd ..",
    "python Stackin/manage.py collectstatic --noinput --settings=Stackin.settings_production"
]

[start]
cmd = "cd Stackin && gunicorn Stackin.wsgi:application --bind 0.0.0.0:$PORT"
